name: CD

on:
  release:
    types: [ created ]

jobs:
  setvar:
    name: Set variables
    runs-on: ubuntu-latest
    steps:
      - name: Get tag version
        run: |
          echo ${GITHUB_REF#refs/*/}
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - uses: actions/checkout@v3
      - name: Get package.json data
        run: |
          echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
    outputs:
      tag: ${{ env.RELEASE_VERSION }}
      version: ${{ fromJson(env.PACKAGE_JSON).version }}

  cd:
    name: Deploy
    needs: setvar
    if: needs.setvar.outputs.version == needs.setvar.outputs.tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
