name: CD

on:
  release:
    types: [ created ]

jobs:
  setvar:
    name: Set variables
    runs-on: ubuntu-latest
    steps:
      - name: Get package.json
        run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
      - name: Get tag version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

  cd:
    name: Deploy
    needs: setvar
    if: ${{ env.RELEASE_VERSION }} == ${{ fromJson(env.PACKAGE_JSON).version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}