name: CD

on:
  release:
    types: [ created ]

jobs:
  setvar:
    name: Set variables
    runs-on: ubuntu-latest
    steps:
      - name: Get package.json
        id: package
        run: |
          ls
          content=`cat ./package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"
      - name: Get tag version
        run: |
          echo ${GITHUB_REF#refs/*/}
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    outputs:
      version: ${{ fromJson(steps.package.outputs.packageJson).version }}
      tag: ${{ env.RELEASE_VERSION }}

  cd:
    name: Deploy
    needs: setvar
    if: ${{ needs.setvar.outputs.version }} == ${{ needs.setvar.outputs.tag }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}